name: versionhelp
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple universal version command # 79 char long summary
description: |
  A simple version command to fetch local and remote version information of any app.
  Example: $version firefox
  * GitHub: https://github.com/prakis/versionhelp
confinement: devmode
base: core18
grade: devel

parts:
  versionhelp:
    plugin: python
    python-version: python2
    source: https://github.com/prakis/versionhelp.git
    stage-packages:
      - python-six